backend:
  name: github
  repo: linuxaddict89/personal-blog
  branch: master
  base_url: https://us-central1-nerdiex-99466.cloudfunctions.net
  auth_endpoint: /oauth/auth
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: content/assets
public_folder: ../assets

collections:
  - name: posts
    label: Post
    folder: content/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: title, label: Title }
      # - { label: Date, name: date, widget: date, format: "YYYY-MM-DD" }
      - { label: Date, name: date, widget: date }
      - { label: Featured Image, name: featuredimage, widget: image }
      - { name: excerpt, label: Excerpt }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { name: body, label: Body, widget: markdown }
